services:
  - type: web
    name: virtual-queue
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class gevent -w 1 app_wrapper:app
    envVars:
      - key: PORT
        value: 10000
      - key: SECRET_KEY
        generateValue: true
      - key: MONGODB_URI
        fromService:
          type: mongodb
          name: virtual-queue-db
          property: connectionString

  - type: mongodb
    name: virtual-queue-db
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere 