services:
  - type: web
    name: virtual-queue
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class gevent -w 1 app:app
    envVars:
      - key: PORT
        value: 10000
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: virtual-queue-db
          property: connectionString

databases:
  - name: virtual-queue-db
    plan: free 